### ISSUE TITLE
server is down = disable domain

### ISSUE THREAD

**Issue by ghost** [J0hnHawk/FS17_WebStats#72]
Hello,
When the server is down, the application will disable the entire domain :(
To try it out, just turn off the dedicated server

Do not you know why?

**Comment by J0hnHawk** [comment]
Mh - seems to be a "Webserver-Thing". Our server is off (we aren't playing since month). If I open my website, FS17 Webstats will show a connections error like it should but it takes a while :-/
![grafik](https://user-images.githubusercontent.com/13779553/42019889-9740cf38-7ab6-11e8-9d5a-557375d78a91.png)

**Comment by J0hnHawk** [comment]
Okay, same here when automatic reload is enabled. When I open the Website the error above occurs. A minute later (automatic reload) the page is blank.

**Comment by ghost** [comment]
yes, an error occurs
thanks :) 👍

**Comment by J0hnHawk** [comment]
I added a condition for automatic reload in templates. Works so far. Could you please test it?

**Comment by ghost** [comment]
Yes it works !!! : D Great job! 👍 

Thank you

**Comment by J0hnHawk** [comment]
Ok. Thanks ^^
